version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: kyiv-access-mongo
    restart: always
    ports:
      - '27017:27017'

    environment:
      MONGO_INITDB_DATABASE: kyiv-access

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: